services:
  node:
    image: node:22-bullseye-slim
    working_dir: /app
    command: sh -c "npm install -g npm && npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
