services:
  backend:
    image: python:3.13-bullseye
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    image: node:22-bullseye-slim
    working_dir: /app
    command: sh -c "npm install -g npm && npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  node_modules:
