services:
  backend:
    image: python:3.13-bullseye
    working_dir: /app
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ORIGINS: ${CORS_ORIGINS}
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host ${BACKEND_HOST} --port ${BACKEND_PORT} --reload"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app

  frontend:
    image: node:22-bullseye-slim
    working_dir: /app
    env_file:
      - .env
    command: sh -c "npm install -g npm && npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  node_modules:
